'use client';
import { useState } from 'react';
import Link from 'next/link';
import * as Dialog from '@radix-ui/react-dialog';
import { Activity, ArrowDownToLine, ArrowRight, BookOpen, CalendarDays, Check, ChevronRight, Database, FileSpreadsheet, GitBranch, Info, LayoutDashboard, LockKeyhole, Menu, MessageSquare, Plus, Settings2, ShieldCheck, SlidersHorizontal, Users, X } from 'lucide-react';
import { aggregate, duration, kpiDefinitions, numberFormat, percent, sampleTeams, sampleTrend } from '../lib/sample-data';
import { TrendChart } from './trend-chart';

type Section = 'dashboard' | 'datasets' | 'kpis' | 'workforce' | 'chat' | 'settings';
const titles: Record<Section, string> = { dashboard: 'Resumen operacional', datasets: 'Datasets', kpis: 'KPI Structure', workforce: 'Directorio de equipos', chat: 'Análisis asistido', settings: 'Administración' };

export function Brand() { return <Link href="/" className="brand" aria-label="ATLAS, inicio"><svg className="brand-symbol" viewBox="0 0 32 32" fill="none" aria-hidden="true"><path d="M3 28 15.7 3 29 28M8 18h16M10 28l6-12 6 12" stroke="currentColor" strokeWidth="1.6" /></svg><span className="brand-word">ATLAS</span><sup>®</sup></Link>; }

export function Workspace() {
  const [section, setSection] = useState<Section>('dashboard');
  const [account, setAccount] = useState('all');
  const [teamId, setTeamId] = useState('all');
  const [showTable, setShowTable] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const [detail, setDetail] = useState<number | null>(null);
  const [notice, setNotice] = useState('');
  const teams = sampleTeams.filter(team => (account === 'all' || team.account === account) && (teamId === 'all' || team.id === teamId));
  const totals = aggregate(teams);
  const values = [percent(totals.serviceLevel), numberFormat.format(totals.calls), duration(totals.aht), percent(totals.quality)];
  const selectedDefinition = detail === null ? null : kpiDefinitions[detail];
  function navigate(next: Section) { setSection(next); setMenuOpen(false); setNotice(''); }
  function exportCsv() {
    const rows = [['Equipo', 'Llamadas ofrecidas', 'Atendidas', 'Nivel de servicio (%)', 'AHT (segundos)', 'Calidad (%)'], ...teams.map(team => [team.name, team.calls, team.answered, (team.service / team.calls * 100).toFixed(2), (team.handleSeconds / team.answered).toFixed(2), (team.qualityPoints / 100).toFixed(2)])];
    const blob = new Blob(['\uFEFF', rows.map(row => row.join(',')).join('\r\n')], { type: 'text/csv;charset=utf-8' });
    const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'atlas-ejemplo-sintetico-2026-08.csv'; link.click(); URL.revokeObjectURL(url);
    setNotice('Ejemplo exportado. El archivo contiene únicamente datos sintéticos.');
  }
  const nav = (id: Section, icon: React.ReactNode, text: string, suffix?: string) => <button className={`nav-item ${section === id ? 'active' : ''}`} onClick={() => navigate(id)} aria-current={section === id ? 'page' : undefined}>{icon}<span>{text}</span>{suffix && <small>{suffix}</small>}</button>;
  return <>
    <header className="header"><button className="icon-button mobile-menu" aria-label={menuOpen ? 'Cerrar navegación' : 'Abrir navegación'} aria-expanded={menuOpen} aria-controls="sidebar" onClick={() => setMenuOpen(!menuOpen)}><Menu /></button><Brand /><div className="header-context"><span className="eyebrow">Espacio de ejemplo</span><span className="badge">DEMO</span></div><div className="header-actions"><span className="status"><span className="status-dot" />Datos sintéticos</span><Link className="button" href="/login"><LockKeyhole size={14} />Ingresar</Link></div></header>
    <div className="app-grid"><aside id="sidebar" className={`sidebar ${menuOpen ? 'is-open' : ''}`} aria-label="Navegación principal"><nav><div className="nav-label">Dashboards</div>{nav('dashboard', <LayoutDashboard />, 'Vista general', '01')}</nav><nav aria-label="Análisis"><div className="nav-label">Análisis</div>{nav('datasets', <Database />, 'Datasets')}{nav('kpis', <GitBranch />, 'KPI Structure')}{nav('chat', <MessageSquare />, 'AI Chat')}</nav><nav aria-label="Personas"><div className="nav-label">Personas</div>{nav('workforce', <Users />, 'Agent Definer')}</nav><nav aria-label="Administración"><div className="nav-label">Administración</div>{nav('settings', <Settings2 />, 'Configuración')}</nav><div className="sidebar-note"><BookOpen size={18} strokeWidth={1.5} /><h3 style={{ marginTop: 10 }}>Tu operación, en contexto.</h3><p>Explora cómo se conectan los datos, las métricas y los equipos.</p><button className="text-button" onClick={() => setDetail(0)}>Explorar un indicador <span aria-hidden="true">↗</span></button></div><div className="sidebar-footer"><span>ATLAS / 0.1</span><span>FUNDACIONES</span></div></aside>
    <main id="main" className="workspace"><div className="breadcrumb"><span>Espacio de ejemplo</span><ChevronRight /><span>{section === 'dashboard' ? 'Dashboards' : titles[section]}</span>{section === 'dashboard' && <><ChevronRight /><span>Vista general</span></>}</div>
      <div className="title-row"><div><div className="eyebrow secondary">{section === 'dashboard' ? 'El pulso de tu operación' : 'ATLAS · Espacio de trabajo'}</div><h1>{titles[section]}</h1><p>{section === 'dashboard' ? 'Una lectura compartida del rendimiento de tus equipos.' : 'Explora la estructura inicial con información de ejemplo.'}</p></div><div className="actions">{section === 'dashboard' ? <><button className="button" onClick={exportCsv}><ArrowDownToLine />Exportar ejemplo</button><Link className="button primary" href="/login"><Plus />Conectar mi operación</Link></> : <button className="button" onClick={() => navigate('dashboard')}><LayoutDashboard />Ver dashboard</button>}</div></div>
      {notice && <p role="status" className="sample-notice"><Check size={14} />{notice}</p>}
      {section === 'dashboard' && <>
        <div className="toolbar"><div className="filters"><div className="filter"><CalendarDays size={15} /><span>25–31 ago, 2026</span></div><div className="filter"><label htmlFor="account">Cuenta</label><select id="account" value={account} onChange={event => { setAccount(event.target.value); setTeamId('all'); }}><option value="all">Todas las cuentas</option><option value="support">Atención al cliente</option><option value="sales">Ventas</option></select></div><div className="filter"><label htmlFor="team">Equipo</label><select id="team" value={teamId} onChange={event => setTeamId(event.target.value)}><option value="all">Todos los equipos</option>{sampleTeams.filter(team => account === 'all' || account === team.account).map(team => <option key={team.id} value={team.id}>{team.name}</option>)}</select></div></div><span className="sample-notice"><Info />Ejemplo · sin datos reales</span></div>
        <div className="kpi-grid" aria-live="polite">{kpiDefinitions.map((definition, index) => <article className="kpi-card" key={definition.id}><div className="kpi-heading"><span>{definition.name}</span><button className="icon-button" aria-label={`Ver definición: ${definition.name}`} onClick={() => setDetail(index)}><Info /></button></div><div className="kpi-value">{values[index]}{index === 2 && <small>min</small>}</div><div className="kpi-change"><Check /><span>{index === 1 ? `${teams.reduce((sum, team) => sum + team.agents, 0)} agentes en equipos de ejemplo` : `Meta de ejemplo: ${definition.target}`}</span></div><div className="kpi-baseline"><span>25—31 AGO</span><button className="text-button" onClick={() => setDetail(index)}>Ver fuente ↗</button></div></article>)}</div>
        <div className="chart-grid"><section className="panel"><div className="panel-header"><div><h2>Tendencia del servicio</h2><p>Serie ilustrativa global · independiente de los filtros</p></div><Activity size={18} className="secondary" /></div><TrendChart /><div className="chart-footer"><span>UNIDAD: % · EJEMPLO SINTÉTICO</span><button className="text-button" onClick={() => setShowTable(!showTable)} aria-expanded={showTable} aria-controls="trend-data">{showTable ? 'Ocultar tabla' : 'Ver tabla de datos'}</button></div>{showTable && <div id="trend-data" className="table-scroll"><table><caption className="sr-only">Tendencia ilustrativa del nivel de servicio</caption><thead><tr><th>Día</th><th className="number">Actual</th><th className="number">Anterior</th></tr></thead><tbody>{sampleTrend.map(row => <tr key={row.day}><td>{row.day}</td><td className="number">{percent(row.current)}</td><td className="number">{percent(row.previous)}</td></tr>)}</tbody></table></div>}</section>
        <section className="panel"><div className="panel-header"><div><h2>Servicio por equipo</h2><p>Llamadas atendidas dentro del umbral</p></div><Users size={18} className="secondary" /></div><div className="performance-body">{teams.map(team => <div className="performance-row" key={team.id}><div className="performance-label"><span>{team.name}</span><strong>{percent(team.service / team.calls * 100)}</strong></div><div className="bar-track" aria-hidden="true"><span className="bar-fill" style={{ width: `${team.service / team.calls * 100}%` }} /></div></div>)}<div className="performance-foot"><span>0%</span><span>│ Meta: 85%</span><span>100%</span></div></div><div className="chart-footer"><span>{teams.length} EQUIPOS EN CONTEXTO</span><button className="text-button" onClick={() => navigate('workforce')}>Ver equipos ↗</button></div></section></div>
        <section className="panel table-panel"><div className="panel-header"><div><h2>Detalle de la operación</h2><p>Indicadores agregados por equipo · datos sintéticos</p></div><span className="badge"><SlidersHorizontal size={12} />{teams.length} equipos</span></div><div className="table-scroll"><table><caption className="sr-only">Resultados de ejemplo por equipo, del 25 al 31 de agosto de 2026</caption><thead><tr><th scope="col">Equipo</th><th scope="col" className="number">Agentes</th><th scope="col" className="number">Llamadas</th><th scope="col" className="number">Servicio</th><th scope="col" className="number">T. gestión</th><th scope="col" className="number">Calidad</th><th scope="col">Meta de servicio</th></tr></thead><tbody>{teams.map(team => <tr key={team.id}><td><span className="team-cell"><span className="team-avatar" aria-hidden="true">{team.initials}</span>{team.name}</span></td><td className="number">{team.agents}</td><td className="number">{numberFormat.format(team.calls)}</td><td className="number">{percent(team.service / team.calls * 100)}</td><td className="number">{duration(team.handleSeconds / team.answered)}</td><td className="number">{percent(team.qualityPoints / 100)}</td><td><span className={`badge ${team.service / team.calls >= .85 ? 'positive' : ''}`}>{team.service / team.calls >= .85 ? <Check size={12} /> : <Info size={12} />}{team.service / team.calls >= .85 ? 'Cumplida' : 'Bajo la meta'}</span></td></tr>)}</tbody></table></div></section>
      </>}
      {section === 'kpis' && <div className="module-list">{kpiDefinitions.map((definition, index) => <article className="module-card" key={definition.id}><span className="badge">Definición de ejemplo</span><h2 style={{ marginTop: 18 }}>{definition.name}</h2><p>{definition.note}</p><button className="text-button" onClick={() => setDetail(index)}>Consultar definición ↗</button></article>)}</div>}
      {section === 'datasets' && <section className="panel table-panel"><div className="panel-header"><div><h2>Catálogo de ejemplo</h2><p>Las cargas reales estarán disponibles al completar el módulo de ingesta.</p></div><FileSpreadsheet size={20} /></div><div className="table-scroll"><table><thead><tr><th>Dataset</th><th>Contenido</th><th>Origen</th><th>Estado</th></tr></thead><tbody><tr><td>Operación semanal</td><td>4 equipos · 2 cuentas</td><td>Fixture sintético integrado</td><td><span className="badge">Demostración</span></td></tr><tr><td>Tendencia del servicio</td><td>7 días · 2 series</td><td>Fixture sintético integrado</td><td><span className="badge">Demostración</span></td></tr></tbody></table></div></section>}
      {section === 'workforce' && <div className="module-list">{sampleTeams.map(team => <article className="module-card" key={team.id}><Users size={22} /><h2 style={{ marginTop: 16 }}>{team.name}</h2><p>{team.account === 'support' ? 'Atención al cliente' : 'Ventas'} · {team.agents} agentes de ejemplo</p><span className="badge">Sin información personal</span></article>)}</div>}
      {section === 'chat' && <section className="empty"><div className="empty-inner"><MessageSquare /><h2>El análisis comienza con tus datos</h2><p>AI Chat estará disponible cuando existan datasets y KPIs publicados. Sus respuestas incluirán fuentes, filtros y versiones utilizadas.</p><span className="badge"><LockKeyhole size={12} />Disponible en una próxima fase</span></div></section>}
      {section === 'settings' && <section className="empty"><div className="empty-inner"><ShieldCheck /><h2>Un espacio para cada organización</h2><p>Ingresa a tu organización para consultar sus cuentas y permisos. Este espacio de ejemplo no permite administrar datos reales.</p><Link href="/login" className="button primary">Ingresar a ATLAS <ArrowRight /></Link></div></section>}
      <footer className="page-footer"><span><ShieldCheck />Ejemplo público · sin conexión a datos de organizaciones</span><span>PERIODO: AGO 2026 · ZONA: AMERICA/GUATEMALA</span></footer>
    </main></div>
    <Dialog.Root open={detail !== null} onOpenChange={open => { if (!open) setDetail(null); }}><Dialog.Portal><Dialog.Overlay className="dialog-overlay" /><Dialog.Content className="dialog-content"><Dialog.Title className="dialog-title">{selectedDefinition?.name}</Dialog.Title><Dialog.Description className="secondary">Definición ilustrativa para explorar la trazabilidad de ATLAS.</Dialog.Description><Dialog.Close className="icon-button dialog-close" aria-label="Cerrar definición"><X /></Dialog.Close>{selectedDefinition && <><dl><dt>Qué mide</dt><dd>{selectedDefinition.note}</dd><dt>Fórmula de ejemplo</dt><dd><code className="formula">{selectedDefinition.formula}</code></dd><dt>Unidad</dt><dd>{selectedDefinition.unit}</dd><dt>Fuente y versión</dt><dd>Fixture sintético local · ejemplo v1</dd><dt>Contexto</dt><dd>25–31 agosto 2026 · America/Guatemala</dd><dt>Publicación</dt><dd>Ejemplo sin publicación en un modelo semántico.</dd></dl><p className="sample-notice"><Info />Las fórmulas de esta vista son texto ilustrativo; no se ejecutan.</p></>}</Dialog.Content></Dialog.Portal></Dialog.Root>
  </>;
}
